### PR TITLE
Forward slash in url 

### PR DESCRIPTION
**Pull request by MikePendo**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/13)

### CODE REVIEW

**Review by udilevin — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/13)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @noambartouv)

**Review by noambartouv — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/13#-:-N7VI3-tDI0g1r47SwPa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MikePendo)

**Review by udilevin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MikePendo)

**Comment by udilevin** [comment]
[merge]

**Comment by pendo-ops** [comment]
JIRA status checks failed:
* [APP-65536](https://pendo-io.atlassian.net/browse/APP-65536): Invalid state 'Backlog' for merge into master

**Comment by udilevin** [comment]
[merge]

**Comment by pendo-ops** [comment]
Some JIRA issues need reviews:
* [APP-65536](https://pendo-io.atlassian.net/browse/APP-65536): Unknown value for the Data Privacy Review field.

**Comment by udilevin** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-65536](https://pendo-io.atlassian.net/browse/APP-65536): Jira Issue APP-65536: Changed to Resolved


Branch APP-65536 deleted

**Pull request merged**
