### PR TITLE
APP-71711 maui instructions

### PR DESCRIPTION
**Pull request by MaximShnirman**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/22)

### CODE REVIEW

**Review by udilevin — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/22)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @MikePendo)

**Review by udilevin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/22)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MikePendo)

**Comment by udilevin** [comment]
:lgtm:[merge]

**Comment by pendo-ops** [comment]
Some linked Jira issues have released fix versions:
* [APP-71711](https://pendo-io.atlassian.net/browse/APP-71711): fix version ios_sdk_2.19.0 was released on 2022-11-21

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-71711](https://pendo-io.atlassian.net/browse/APP-71711): Resolved


Branch APP-71711_MAUI deleted

**Pull request merged**
