### PR TITLE
App 80331

### PR DESCRIPTION
**Pull request by udilevin**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/32)

### CODE REVIEW

**Comment by MikePendo** [comment]
*[`pnddocs/expo.md` line 80 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/32#-NTTgvT74aLNto6aqrJe:-NTTgvT88DMnXkTq7NtD:b-p2cnbc) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/7bbf6b1fce5125d4fa7d4e64210f07c03bcf7105/pnddocs/expo.md#L80)):*
> ```Markdown
> 
> ```typescript
>     const PendoNavigationContainer = WithPendoReactNavigation(NavigationContainer);    
> ```

@udilevin I am slightly confused, in the previous integration `withPendoRN` we had an option to provide parameters like `nativeIDs` etc where is the option here? can u add a sample code as well?

**Comment by MikePendo** [comment]
*[`pnddocs/expo.md` line 83 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/32#-NTTiKWy9u6FAc23q4U5:-NTTiKWy9u6FAc23q4U6:b-ci8qyq) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/7bbf6b1fce5125d4fa7d4e64210f07c03bcf7105/pnddocs/expo.md#L83)):*
> ```Markdown
> ```
> 
>     replace `NavigationContainer` tag with `PendoNavigationContainer` tag
> ```

This whole part looks like a code but its not



_Code quote:_
```Markdown
replace `NavigationContainer` tag with `PendoNavigationContainer` tag
```

**Comment by MikePendo** [comment]
*[`pnddocs/expo.md` line 80 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/32#-NTTgvT74aLNto6aqrJe:-NTTiVYGE5OTF7sE3nAp:b-ppheks) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/7bbf6b1fce5125d4fa7d4e64210f07c03bcf7105/pnddocs/expo.md#L80)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

@udilevin I am slightly confused, in the previous integration `withPendoRN` we had an option to provide parameters like `nativeIDs` etc where is the option here? can u add a sample code as well?
</blockquote></details>

Sorry saw it

**Comment by MikePendo** [comment]
*[`pnddocs/expo_native_navigation.md` line 77 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/32#-NTTjkCb-Yh7XDzTGqyu:-NTTjkCb-Yh7XDzTGqyv:b23ijie) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/7bbf6b1fce5125d4fa7d4e64210f07c03bcf7105/pnddocs/expo_native_navigation.md#L77)):*
> ```Markdown
> ## Limitations 
> Please note **Expo Go** is not supported by Pendo because Pendo SDK has a native plugin which is not part of the Expo Go app.
> Pendo can be used in development builds *only*. 
> ```

is `only` in correct place? for some reason .md doest show it as bold.

**Review by MikePendo — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/32)* status: all files reviewed, 3 unresolved discussions (waiting on @udilevin)

**Comment by MikePendo** [comment]
:lgtm:

**Review by udilevin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/32)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @MikePendo)

___
*[`pnddocs/expo.md` line 77 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/32#-NTTi82Y3Metg9VA2bgA:-NTTnv1-CUK5dLb8mT_7:bb6un1j) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/7bbf6b1fce5125d4fa7d4e64210f07c03bcf7105/pnddocs/expo.md#L77)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

This whole part looks like a code BUT it not 
</blockquote></details>

Done
___
*[`pnddocs/expo.md` line 83 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/32#-NTTiKWy9u6FAc23q4U5:-NTTnzrW3M8uYLt_J53a:b-95txdl) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/7bbf6b1fce5125d4fa7d4e64210f07c03bcf7105/pnddocs/expo.md#L83)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

This whole part looks like a code but its not
</blockquote></details>


Done
___
*[`pnddocs/expo_native_navigation.md` line 55 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/32#-NTTiyNk5pglz1qMhUD5:-NTTo0TlDx0XmlwWMoh4:bkk1pwl) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/7bbf6b1fce5125d4fa7d4e64210f07c03bcf7105/pnddocs/expo_native_navigation.md#L55)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

I forgot why we need to wrap it with `Navigation.events().registerAppLaunchedListener(` and not just call it as is (NON BLOCKING)
</blockquote></details>

That's the earliest place to place Pendo, before RNN starts anything (best practice)
___
*[`pnddocs/expo_native_navigation.md` line 77 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/32#-NTTjkCb-Yh7XDzTGqyu:-NTToIoU4C3q9ZY01S4q:bb6un1j) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/7bbf6b1fce5125d4fa7d4e64210f07c03bcf7105/pnddocs/expo_native_navigation.md#L77)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

is `only` in correct place? for some reason .md doest show it as bold.
</blockquote></details>

Done

**Comment by MikePendo** [comment]
:lgtm:

**Review by MikePendo — APPROVED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/32)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @udilevin)

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-80331](https://pendo-io.atlassian.net/browse/APP-80331): Jira Issue APP-80331: Changed to Resolved


Branch APP-80331 deleted

**Pull request merged**
