### PR TITLE
APP-76862 Swiftui update docs

### PR DESCRIPTION
**Pull request by MikePendo**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[6d839a4](https://github.com/pendo-io/pendo-mobile-ios/pull/30/commits/6d839a4a80f13e5ec36bf3eeb8389d596d8d2088)

**Comment by udilevin** [comment]
*[`pnddocs/swiftui.md` line 53 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-NR86RQm4i5nfU9jFIKU:-NR86RQm4i5nfU9jFIKV:bcq5f6x) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/6d839a4a80f13e5ec36bf3eeb8389d596d8d2088/pnddocs/swiftui.md#L53)):*
> ```Markdown
>                     Text("Text")
>                 }
>             }
> ```

Let's wait with these instructions. I have an alternate idea. Let's discuss.

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[6d839a4](https://github.com/pendo-io/pendo-mobile-ios/pull/30/commits/6d839a4a80f13e5ec36bf3eeb8389d596d8d2088)
[faa4427](https://github.com/pendo-io/pendo-mobile-ios/pull/30/commits/faa442783b5c2f6624fd6da5fa1a6e53070a9604)

**Comment by cohenam** [comment]
[checks]

**Comment by cohenam** [comment]
[check]

**Comment by pendo-ops** [comment]
Okay, All checks were run. Did not encounter any errors.

**Review by MaximShnirman — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30)* status: all files reviewed, 1 unresolved discussion (waiting on @MikePendo)

**Comment by MikePendo** [comment]
[check]

**Comment by pendo-ops** [comment]
Okay, All checks were run. Did not encounter any errors.

**Review by noambartouv — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30)* status: 0 of 1 files reviewed, 12 unresolved discussions (waiting on @MaximShnirman and @MikePendo)

___
*[`pnddocs/swiftui.md` line 3 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-NTKiAW23rEuN60RoWAR:-NTKiAW3C8x0MYg4OYFG:btxe2iw) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/934d9fe00694f1752b92578b95a90f8a445432d5/pnddocs/swiftui.md#L3)):*
> ```Markdown
> # SwiftUI Integration 
> Currently SwiftUI support is provided as beta and is available via cocoapods and SPM:<br>
> The codeless solution is supported with IOS 15 and 16. Screen tracking is available since IOS 13. (For Iphones)
> ```

Maybe change the term "Screen tracking" to "Screen navigation tracking?"
___
*[`pnddocs/swiftui.md` line 3 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-NTKiPUd8Dyk2_J1_YS6:-NTKiPUd8Dyk2_J1_YS7:bllrdgt) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/934d9fe00694f1752b92578b95a90f8a445432d5/pnddocs/swiftui.md#L3)):*
> ```Markdown
> # SwiftUI Integration 
> Currently SwiftUI support is provided as beta and is available via cocoapods and SPM:<br>
> The codeless solution is supported with IOS 15 and 16. Screen tracking is available since IOS 13. (For Iphones)
> ```

What does the "(For Iphones)" mean? This is swiftUI, what other phones would it be?
___
*[`pnddocs/swiftui.md` line 3 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-NTKiYIy5l5SPt6qn5JS:-NTKiYIy5l5SPt6qn5JT:bbn4z0r) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/934d9fe00694f1752b92578b95a90f8a445432d5/pnddocs/swiftui.md#L3)):*
> ```Markdown
> # SwiftUI Integration 
> Currently SwiftUI support is provided as beta and is available via cocoapods and SPM:<br>
> The codeless solution is supported with IOS 15 and 16. Screen tracking is available since IOS 13. (For Iphones)
> ```

What will happen when iOS 17 comes out? Should we change the text from iOS 15 and 16 change to iOS 15 or newer?
___
*[`pnddocs/swiftui.md` line 35 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-NTKj13kCL0hEv84Cova:-NTKj13kCL0hEv84Covb:boatmd3) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/934d9fe00694f1752b92578b95a90f8a445432d5/pnddocs/swiftui.md#L35)):*
> ```Markdown
> ```
> 
> To enable Pendo in your SwiftUI view, use the `enableSwiftUI()` modifier on your `rootView`.
> ```

When do our customers use this? Custom views? (to me it's not clear) What does enabling Pendo mean?
___
*[`pnddocs/swiftui.md` line 90 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-NTKjcRU4RoHWaQgc-dU:-NTKjcRU4RoHWaQgc-dV:b-ut5szq) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/934d9fe00694f1752b92578b95a90f8a445432d5/pnddocs/swiftui.md#L90)):*
> ```Markdown
> 
> ## Accessibility Support
> In case you don't add accessibility modifiers ios will generate a default ones based on the ui elements of your app.
> ```

Grammer fix: 
If you don't add accessibility modifiers the OS will assign default values to the UI elements in your app.

(might be worth changing accessibility to accessibility labels (not aware that the OS sets default values for identifiers or hints)
___
*[`pnddocs/swiftui.md` line 91 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-NTKkAVnDewsvcRHjFTn:-NTKkAVoEaEv7iN38azM:bqmyfnt) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/934d9fe00694f1752b92578b95a90f8a445432d5/pnddocs/swiftui.md#L91)):*
> ```Markdown
> ## Accessibility Support
> In case you don't add accessibility modifiers ios will generate a default ones based on the ui elements of your app.
> We should have the support of label/identifier/hint. <br>
> ```

I think what you were trying to say something like:
"Accessibility identifiers, accessibility labels, and accessibility hints are all supported and can be used by Pendo for unique identification."
___
*[`pnddocs/swiftui.md` line 110 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-NTKl9Rl75LJfYZhwrey:-NTKl9Rl75LJfYZhwrez:bs71puz) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/934d9fe00694f1752b92578b95a90f8a445432d5/pnddocs/swiftui.md#L110)):*
> ```Markdown
> 
> ## SwiftUI In UIKit 
> SwiftUI is represented by `UIHostingController` when its embeded in UIKit the support is default SwiftUI support.
> ```

I don't understand this sentence. I understand SwiftUI is contained within a UIHostingController but don't understand the general context here. Guessing that maybe we're talking about transitioning an app from UIKit to include SwiftUI as well.
___
*[`pnddocs/swiftui.md` line 113 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-NTKm3J_D8QFUEhTgBzI:-NTKm3J_D8QFUEhTgBzJ:bdc9i4) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/934d9fe00694f1752b92578b95a90f8a445432d5/pnddocs/swiftui.md#L113)):*
> ```Markdown
> 
> ## Limitation 
> :technologist: - Dynamic Content (content that appears after your screen was loaded, like data loaded from server) currently not supported, please use `screenContentChanged` for those screens <br>
> ```

grammer fix:
"..., please use `screenContentChanged` api for such screens"
___
*[`pnddocs/swiftui.md` line 114 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-NTKmQOrCJZW4soHAiCG:-NTKmQOrCJZW4soHAiCH:b-eo0s8b) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/934d9fe00694f1752b92578b95a90f8a445432d5/pnddocs/swiftui.md#L114)):*
> ```Markdown
> ## Limitation 
> :technologist: - Dynamic Content (content that appears after your screen was loaded, like data loaded from server) currently not supported, please use `screenContentChanged` for those screens <br>
> :technologist: - Clickable elements buttons/tapGestures etc. When you create a clickable element that doesn't has background color of its own like VStack, HStack please set a background color to it that is NOT transparent<br>
> ```

grammar fix:
Clickable elements buttons/tapGestures etc. When creating clickable elements that don't have a background color set on them (e.x. VStack or HStack) please set a background color to them that is NOT transparent



_Code quote:_
```Markdown
Clickable elements buttons/tapGestures etc. When you create a clickable element that doesn't has background color of its own like VStack, HStack please set a background color to it that is NOT transparent
```
___
*[`pnddocs/swiftui.md` line 120 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-NTKmxyc7OCWImsD0Vq_:-NTKmxyc7OCWImsD0Vqa:b-pp9mnf) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/934d9fe00694f1752b92578b95a90f8a445432d5/pnddocs/swiftui.md#L120)):*
> ```Markdown
> ## NOTE
> We are highly recommend to use the following sample apps to tag features and see how Pendo ananlytics works.<br>
> (Please pay attention: to *PENDO CHANGE* comments where in some places we needed to have a minor changes like integration code or background color)<br>
> ```

Grammar fix:
We highly recommend checking out the following sample apps to observe examples of feature tagging and how Pendo analytics work.<br> (Please pay attention to comments with *PENDO CHANGE* which in some places require minor changes like integration code or adding a background color)<br>
___
*[`pnddocs/swiftui.md` line 126 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-NTKnq_c4F_wx2JHnYdK:-NTKnq_c4F_wx2JHnYdL:b-3me7ki) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/934d9fe00694f1752b92578b95a90f8a445432d5/pnddocs/swiftui.md#L126)):*
> ```Markdown
> 
> 
> IF you find any issue with swiftUI please open a github ticket with minimal code sample so we could reproduce it.
> ```

Grammar fix:
If you encounter issues using SwiftUI please open a GitHub ticket with the minimal sample code required to reproduce it.

**Review by noambartouv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @MaximShnirman and @MikePendo)

___
*[`pnddocs/swiftui.md` line 3 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-NTKiPUd8Dyk2_J1_YS6:-NTMCkum50dZX6zi4R7P:bm1paog) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/934d9fe00694f1752b92578b95a90f8a445432d5/pnddocs/swiftui.md#L3)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

we didn't have proper tests for iPads
</blockquote></details>

Then it should say that:
The full codeless solution is supported by iOS 15 and above. Screen navigation tracking is available from iOS 13. (Testing has focused on iPhones. iPads have yet to be tested thoroughly)
___
*[`pnddocs/swiftui.md` line 3 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-NTKiYIy5l5SPt6qn5JS:-NTMDQfd-cwnLNuRcakj:b-cle8av) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/934d9fe00694f1752b92578b95a90f8a445432d5/pnddocs/swiftui.md#L3)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

I dont know, we need to test for iOS 17
</blockquote></details>

IOS 17 is currently beta. I think we should just say iOS 15 and newer it the docs and make sure do perform proper testing for new OS versions before their release (we usually do as far as I remember)
___
*[`pnddocs/swiftui.md` line 35 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-NTKj13kCL0hEv84Cova:-NTMEME07pNxGryRUYoE:bi9yq3g) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/934d9fe00694f1752b92578b95a90f8a445432d5/pnddocs/swiftui.md#L35)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

what do u suggest? we have code example later on 
</blockquote></details>

The context in which a user would use the API is not clear. Its clear how to use it, not when it is required. I don't understand myself when would I need/want to call this.

**Review by noambartouv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @MaximShnirman and @MikePendo)

___
*[`pnddocs/swiftui.md` line 35 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-NTKj13kCL0hEv84Cova:-NTMFC8z8e2c98Q3vKtm:b7wdbi7) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/934d9fe00694f1752b92578b95a90f8a445432d5/pnddocs/swiftui.md#L35)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

The context in which a user would use the API is not clear. Its clear how to use it, not when it is required. I don't understand myself when would I need/want to call this.
</blockquote></details>

I now watched the video. This should probably say:
To support SwiftUI the Pendo SDK requires you to apply the`enableSwiftUI()` modifier on each one of the rootViews in your app. See example below:

**Comment by MikePendo** [comment]
*[`pnddocs/swiftui.md` line 3 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-NTKiYIy5l5SPt6qn5JS:-NTOSmER3lbzXeN6mSa3:bn1vjc8) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/934d9fe00694f1752b92578b95a90f8a445432d5/pnddocs/swiftui.md#L3)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

IOS 17 is currently beta. I think we should just say iOS 15 and newer it the docs and make sure do perform proper testing for new OS versions before their release (we usually do as far as I remember)
</blockquote></details>

and if iOS 17 will not work? u suggest to change the docs?

**Comment by MikePendo** [comment]
*[`pnddocs/swiftui.md` line 35 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-NTKj13kCL0hEv84Cova:-NTOSyBp5XWg6JwPRnUw:b-fvced2) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/934d9fe00694f1752b92578b95a90f8a445432d5/pnddocs/swiftui.md#L35)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

I now watched the video. This should probably say:
To support SwiftUI the Pendo SDK requires you to apply the`enableSwiftUI()` modifier on each one of the rootViews in your app. See example below: 
</blockquote></details>

but in general u will have only one rootView. OR u might have

**Comment by MikePendo** [comment]
*[`pnddocs/swiftui.md` line 110 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-NTKl9Rl75LJfYZhwrey:-NTLUjXv-D3ogP-FT31G:b8hv1zk) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/934d9fe00694f1752b92578b95a90f8a445432d5/pnddocs/swiftui.md#L110)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

I don't understand this sentence. I understand SwiftUI is contained within a UIHostingController but don't understand the general context here. Guessing that maybe we're talking about transitioning an app from UIKit to include SwiftUI as well.
</blockquote></details>

its SwiftUI inside  uikit

**Comment by MikePendo** [comment]
*[`pnddocs/swiftui.md` line 3 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-NTKiAW23rEuN60RoWAR:-NTLS0ng1Ew_s0CBErjx:b-ocwy7) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/934d9fe00694f1752b92578b95a90f8a445432d5/pnddocs/swiftui.md#L3)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Maybe change the term "Screen tracking" to "Screen navigation tracking?"
</blockquote></details>

not sure how its better

**Review by noambartouv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @MaximShnirman and @MikePendo)

___
*[`pnddocs/swiftui.md` line 3 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-NTKiYIy5l5SPt6qn5JS:-NTP2xCE0TXW2cwXDWOW:b-5a8daz) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/934d9fe00694f1752b92578b95a90f8a445432d5/pnddocs/swiftui.md#L3)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

and if iOS 17 will not work? u suggest to change the docs?
</blockquote></details>

Yes or we do the work to support iOS 17 (as it will probably be highly prioritized by product)
___
*[`pnddocs/swiftui.md` line 3 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-NTKiPUd8Dyk2_J1_YS6:-NTP37_W-LXxXhDkRzsv:b-xpunds) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/934d9fe00694f1752b92578b95a90f8a445432d5/pnddocs/swiftui.md#L3)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

@noambartouv  its to long... 
</blockquote></details>

A little longer and clear is better than short and not clear :shrug:

**Review by udilevin — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MikePendo)

**Review by noambartouv — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30#-:-NTPq7BZ3QVm4GaX3jQm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MikePendo)

**Comment by noambartouv** [comment]
[merge]

**Comment by MikePendo** [comment]
[checks]

**Review by orendayan — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MikePendo)

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-76862](https://pendo-io.atlassian.net/browse/APP-76862): Jira Issue APP-76862: Changed to Resolved


Branch APP-76862 deleted

**Pull request merged**
