### PR TITLE
Swift UI docs update

### PR DESCRIPTION
**Pull request by MikePendo**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/15)

### CODE REVIEW

**Review by udilevin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MikePendo)

**Comment by udilevin** [comment]
[merge]

**Comment by pendo-ops** [comment]
JIRA status checks failed:
* [APP-64803](https://pendo-io.atlassian.net/browse/APP-64803): Branch mismatch: target branch  in JIRA not valid for master merge type

**Comment by udilevin** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-64803](https://pendo-io.atlassian.net/browse/APP-64803): Jira Issue APP-64803: Changed to Resolved


Branch APP-64803 deleted

**Pull request merged**
