### PR TITLE
APP-80673

### PR DESCRIPTION
**Pull request by MikePendo**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/34)

### CODE REVIEW

**Review by udilevin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/34)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MaximShnirman)

**Review by MaximShnirman — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/34)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MikePendo)

**Review by MaximShnirman — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/34)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MikePendo)

**Comment by MaximShnirman** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-80673](https://pendo-io.atlassian.net/browse/APP-80673): Jira Issue APP-80673: Changed to Resolved


Branch APP-80673 deleted

**Pull request merged**
