### PR TITLE
APP-80950 fix url sample app 

### PR DESCRIPTION
**Pull request by MikePendo**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/36)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[141152b](https://github.com/pendo-io/pendo-mobile-ios/pull/36/commits/141152bd9344aeaa20fe275fe87a80c773240740)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[3bfda84](https://github.com/pendo-io/pendo-mobile-ios/pull/36/commits/3bfda84efe20e60e21f8b961a54fa5dfec73b315)

**Review by 0xkuj — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/36)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MikePendo)

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-80950](https://pendo-io.atlassian.net/browse/APP-80950): Jira Issue APP-80950: Changed to Resolved


Branch APP-80950 deleted

**Pull request merged**
