### PR TITLE
Changing documentation for SwiftUI beta

### PR DESCRIPTION
**Pull request by MikePendo**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/12)

### CODE REVIEW

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct missing Jira references in the following commits:

[113ff71](https://github.com/pendo-io/pendo-mobile-ios/pull/12/commits/113ff717cc49668a60f14159c4e39aea08b31d81)
[2b0062e](https://github.com/pendo-io/pendo-mobile-ios/pull/12/commits/2b0062e9f21a018a5f0bd76dae50b9810704f6f5)
[35de73f](https://github.com/pendo-io/pendo-mobile-ios/pull/12/commits/35de73f5b281722e01a2144eb6378302d9a63641)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct missing Jira references in the following commits:

[a7da8d9](https://github.com/pendo-io/pendo-mobile-ios/pull/12/commits/a7da8d920a951492357d81088ccf16007dbd935e)
[d21194b](https://github.com/pendo-io/pendo-mobile-ios/pull/12/commits/d21194be6b1de741a409d78b8fc294d006bdaa68)
[e708efc](https://github.com/pendo-io/pendo-mobile-ios/pull/12/commits/e708efc4aaf2667cac916c39658135d722aae489)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct missing Jira references in the following commits:

[a7da8d9](https://github.com/pendo-io/pendo-mobile-ios/pull/12/commits/a7da8d920a951492357d81088ccf16007dbd935e)
[d21194b](https://github.com/pendo-io/pendo-mobile-ios/pull/12/commits/d21194be6b1de741a409d78b8fc294d006bdaa68)
[e708efc](https://github.com/pendo-io/pendo-mobile-ios/pull/12/commits/e708efc4aaf2667cac916c39658135d722aae489)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct missing Jira references in the following commits:

[a7da8d9](https://github.com/pendo-io/pendo-mobile-ios/pull/12/commits/a7da8d920a951492357d81088ccf16007dbd935e)
[d21194b](https://github.com/pendo-io/pendo-mobile-ios/pull/12/commits/d21194be6b1de741a409d78b8fc294d006bdaa68)
[e708efc](https://github.com/pendo-io/pendo-mobile-ios/pull/12/commits/e708efc4aaf2667cac916c39658135d722aae489)

**Review by udilevin — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MikePendo)

**Comment by pendo-ops** [comment]
Failed pendo.io/jira-ref check. Please correct missing Jira references in the following commits:

[8a38c43](https://github.com/pendo-io/pendo-mobile-ios/pull/12/commits/8a38c43969473fb714e527ad87927a396f465a35)

**Review by noambartouv — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/12#-:-N7UzM8i59EvjV-AQ0aQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MikePendo)

**Comment by noambartouv** [comment]
[merge]

**Comment by pendo-ops** [comment]
JIRA status checks failed:
* [APP-64804](https://pendo-io.atlassian.net/browse/APP-64804): Invalid state 'Backlog' for merge into master

**Comment by noambartouv** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-64804](https://pendo-io.atlassian.net/browse/APP-64804): Jira Issue APP-64804: Changed to Resolved


Branch APP-64804 deleted

**Pull request merged**
