### PR TITLE
Expo docs

### PR DESCRIPTION
**Pull request by MikePendo**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/20)

### CODE REVIEW

**Comment by udilevin** [comment]
*[`pnddocs/expo.md` line 1 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/20#-NH0oDmTA_rbdNuJMLsf:-NH0oDmTA_rbdNuJMLsg:b-h20p6g) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/c9c0e75cff2697f7e53ad684712dc622df219d2d/pnddocs/expo.md#L1)):*
> ```Markdown
> ## Expo IOS
> ```

Move expo go to the bottom
Mention that expo sdk 41 or above is required

**Comment by udilevin** [comment]
*[`pnddocs/expo.md` line 29 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/20#-NH0oOKa58pNFmuV5wBu:-NH0oOKa58pNFmuV5wBv:ba2gs4y) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/c9c0e75cff2697f7e53ad684712dc622df219d2d/pnddocs/expo.md#L29)):*
> ```Markdown
>       [
>         "rn-pendo-sdk",
>         {
> ```

Rename to YOUR_IOS_URL_SCHEME
YOUR_ANDROID_URL_SCHEME

**Comment by MikePendo** [comment]
*[`pnddocs/expo.md` line 29 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/20#-NH0oOKa58pNFmuV5wBu:-NH0rLkQ7V4Lp1QuRTAK:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/c9c0e75cff2697f7e53ad684712dc622df219d2d/pnddocs/expo.md#L29)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

Rename to YOUR_IOS_URL_SCHEME
YOUR_ANDROID_URL_SCHEME
</blockquote></details>

Done.

**Comment by MikePendo** [comment]
*[`pnddocs/expo.md` line 1 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/20#-NH0oDmTA_rbdNuJMLsf:-NH0rMmZ5_echPWiyIjO:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/c9c0e75cff2697f7e53ad684712dc622df219d2d/pnddocs/expo.md#L1)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

Move expo go to the bottom
Mention that expo sdk 41 or above is required
</blockquote></details>

Done.

**Comment by udilevin** [comment]
*[`pnddocs/expo.md` line 111 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/20#-NH4bSSs2ysfxxskaAR3:-NH4bSSs2ysfxxskaAR4:bidgloa) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/ba24a118ece81fed0ae4c74578efcbdb3b49e575/pnddocs/expo.md#L111)):*
> ```Markdown
> 
> ## Limitations 
> Please note **Expo Go** is not supported by Pendo because Pendo SDK has a native plugin which is not part of the Expo Go app.
> ```

I think you should mention that we you can develop app integrated with Pendo in Expo Go (we don't crash).

**Comment by MikePendo** [comment]
*[`pnddocs/expo.md` line 111 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/20#-NH4bSSs2ysfxxskaAR3:-NH5G2Ng-5YMedJb0HrS:bfk96fv) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/ba24a118ece81fed0ae4c74578efcbdb3b49e575/pnddocs/expo.md#L111)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

I think you should mention that we you can develop app integrated with Pendo in Expo Go (we don't crash).
</blockquote></details>

mmm not sure about the value ... its kinda obviously that u should not crash

**Comment by udilevin** [comment]
*[`pnddocs/expo.md` line 111 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/20#-NH4bSSs2ysfxxskaAR3:-NHK9IO8EIcIQs2wiLmz:b-up72b3) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/ba24a118ece81fed0ae4c74578efcbdb3b49e575/pnddocs/expo.md#L111)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

mmm not sure about the value ... its kinda obviously that u should not crash 
</blockquote></details>

You mention that you need to use development builds only, but that's incorrect, I can use Expo Go build and just not get Pendo data.

**Review by MaximShnirman — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/20)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @MikePendo, @noambartouv, @OfreeWeisman, and @udilevin)

**Review by udilevin — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/20)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @noambartouv and @OfreeWeisman)

**Review by udilevin — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noambartouv and @OfreeWeisman)

**Comment by udilevin** [comment]
:lgtm:[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-70670](https://pendo-io.atlassian.net/browse/APP-70670): Jira Issue APP-70670: Changed to Resolved


Branch APP-70670 deleted

**Comment by MikePendo** [comment]
*[`pnddocs/expo.md` line 111 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/20#-NH4bSSs2ysfxxskaAR3:-NHPGqYACjVtXci0MjS1:b-t58ly1) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/ba24a118ece81fed0ae4c74578efcbdb3b49e575/pnddocs/expo.md#L111)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

You mention that you need to use development builds only, but that's incorrect, I can use Expo Go build and just not get Pendo data.
</blockquote></details>

But u cant use pendo in ExpoGo what the value of pendo ?

**Pull request merged**
