### PR TITLE
SwiftUI official

### PR DESCRIPTION
**Pull request by MikePendo**
This change is [Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/16)

### CODE REVIEW

**Comment by udilevin** [comment]
*[`README.md` line 18 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/16#-NBDbQkB1QwbWScLGsvP:-NBDbQkB1QwbWScLGsvQ:bfnmzkz) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/b227eaf882b50d98eb9e9bd1957dadaf596e3138/README.md#L18)):*
> ```Markdown
> 
> ## Installation Instructions 
> - [Native IOS](/pnddocs/native.md)
> ```

Rename swift_beta.md to swift.md

**Comment by MikePendo** [comment]
*[`README.md` line 18 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/16#-NBDbQkB1QwbWScLGsvP:-NBgCwUgES9NH8vTS94B:bb6un1j) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/b227eaf882b50d98eb9e9bd1957dadaf596e3138/README.md#L18)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

Rename swift_beta.md to swift.md
</blockquote></details>

Done

**Comment by MikePendo** [comment]
*[`pnddocs/swiftui_beta.md` line 4 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/16#-NBCtVyvAh9rVko6X0GQ:-NBgDmKt1vdgTE5nos2H:b-elay57) ([raw file](https://github.com/pendo-io/pendo-mobile-ios/blob/7f05e1d647b5c71c9c617cf016c244ccfc54130b/pnddocs/swiftui_beta.md#L4)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

bring back the tag for Cocoapods. Only the source should be removed
</blockquote></details>

Done TNX

**Review by 0xkuj — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/16)* status: all files reviewed, 1 unresolved discussion (waiting on @udilevin)

**Review by noambartouv — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/16#-:-NBgfX3F-6SlXti-YKu4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @udilevin)

**Review by udilevin — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MikePendo)

**Comment by noambartouv** [comment]
[merge]

**Comment by pendo-ops** [comment]
All JIRA issue transitioned/labeled.
* [APP-67995](https://pendo-io.atlassian.net/browse/APP-67995): Jira Issue APP-67995: Changed to Resolved


Branch APP-67995 deleted

**Pull request merged**
